name    'gehel-kiosk'
version '1.0.0'
author  'Guillaume Lederrey'
license 'Apache2'
project_page ''
source  'https://github.com/gehel/puppet-kiosk'
summary 'Puppet module for kiosk'
description 'This module installs and manages kiosk. Check README for details.'
dependency 'example42/puppi', '>= 2.0.0'
dependency 'puppetlabs/stdlib', '4.1.0'
dependency 'example42/rclocal', '>=2.0.0'
# dependency 'example42/monitor', '>= 2.0.0'
# dependency 'example42/firewall', '>= 2.0.0'
